name: Sample SRC Workflow
# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch
jobs:
  sample-src-test:
    runs-on: ubuntu-latest
    steps:
      # every steps name start with -
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
      - name: Run Test Cases
        run: pytest sample_src/
              
