name: Multiple jobs and Event
# Allows you to run this workflow manually from the Actions tab
on: [push,workflow_dispatch]
jobs:
  First:
    # runs-on: on which machine that job will run.  
    runs-on: ubuntu-latest
    steps:
      # every steps name start with -
      - name: Get Code
      #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. 
        uses: actions/checkout@v4
      - name: Install Python 3.12
      # This action provides : Installing a version of Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
      - name: Run Test Cases
        run: pytest sample_src/
              
  Second:
      runs-on: ubuntu-latest
      steps:
        # every steps name start with -
        - name: Print greeting
          run: echo " Hi, This is first workflow steps"
        - name: Print Goodbye
          run: echo " Goodbye workflow"
  Final:
      needs : [First,Second]
      runs-on: ubuntu-latest
      steps:
        # every steps name start with -
        - name: Deploye Code
        # Print Environment inbuilt Variable
          run: echo " Deploye the Code: ${{ github }}"
