name: Pull Push Request Event Workflow
on:
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
  pull_request:
    types:
      - opened
    branches:
      - main  #main
      - 'dev-*' #dev-new,dev-this
  workflow_dispatch:
  push:
    branches:
      - 'feature'
    paths-ignore:
      - '.github/workflows/.*'  # ignore workflow if changes happen in this path
jobs:
  Deploye102:
    # runs-on: on which machine that job will run.  
    runs-on: ubuntu-latest
    steps:
      # every steps name start with -
      - name: Get Code
      #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. 
        uses: actions/checkout@v4
      - name: Install Python 3.12
      # This action provides : Installing a version of Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
      - name: Run Test Cases
        run: pytest sample_src/
              